:icons: font
:source-highlighter: highlightjs
:numbered:
:toc: left
:toclevels: 3


= 包妈课堂接口文档
chenjunqiang <chenjunqiang@xxbmm.com>
v1.0 2018-07-06


== 相关类别
=== 基础响应信息
[cols="4", options="header"]
|===
|参数|类型|说明|示例
|`success`|`boolean`|返回结果状态。true：成功；false：失败。|`true`
|`msg`|`String`|提示信息|操作成功
|`code`|`Integer`|响应码，可选|`0`
|`nowDate`|`Long`|当前时间戳|`1530773758000`
|`data`|`Object`|响应数据|`null`
|===
[#flowerType,asdsa]
=== 小红花记录类型
[cols="3", options="header"]
|===
|类型|值|描述
|课程兑换|`1`|兑换课程
|每日签到|`2`|每日签到
|连续签到|`3`|每连续签到7日
|邀请新用户|`4`|成功邀请新用户
|观看课程超过3分钟|`5`|观看课程超过3分钟，每节课持续观看超过3分钟
|发表留言|`6`|发表留言通过审核
|留言被推荐|`7`|留言被推荐
|留言被老师回复|`8`|留言被老师回复
|分享课程给好友|`9`|分享课程给好友
|分享课程被好友点击|`10`|分享课程被好友点击
|看完专辑课程|`11`|看完专辑课程，每看完一节课
|===

== 用户
=== 用户接口
==== 查询用户信息
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/{id}`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`id(path)`|`Integer`|`true`|用户编号
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1531127611915,
    "ver": 0,
    "data": {
        "id": 16,
        "name": "chenjq", //用户姓名
        "phone": "18310022931", //手机号码
        "headImage": "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1461547269,2212657881&fm=27&gp=0.jpg", //头像url地址
        "flower": 52, //小红花数量
        "openId": "sadsalk1@ewq!!dsa", //openId
        "unionId": "aabbbcc", //unionId
        "status": 0, //冻结状态,0-正常，1-冻结
        "createTime": 1530773758000 //添加时间
    }
}
----
=== 用户红花接口
==== 小红花记录分页查询
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/page`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`page`|`Integer`|`true`|当前页
|`pageSize`|`Integer`|`true`|每页数量
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": {
        "list": [
            {
              "id": 3 ,
              "userId": 16 ,  //用户编号
              "type": 1 , //类型值
              "objectId": 123 , //关联编号
              "friendUserId": 123 , //好友编号
              "description": "兑换课程,减少100积分，用户Id:{16},关联ID:{123}" , //记录描述
              "flower": 100 , //小红花数量
              "createTime": 1530773758000 , //添加时间
              "typeName": "课程兑换" , //类型名称
              "directionIcon": "-"  //扣减方向符号 +、-
            }
        ],
        "pageNum": 1,
        "pageSize": 2,
        "size": 2,
        "pages": 1,
        "total": 2,
        "hasNextPage": false
    }
}
----

==== 查询当日签到状态
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/signStatus`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": true  //签到状态 true、false
}
----

==== 更新小红花接口
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/`|`POST`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`type`|`Integer`|`true`|记录类型 详细请阅读<<flowerType>>
|`objectId`|`Integer`|`false`|关联ID
|`friendUserId`|`Integer`|`false`|好友ID
|`flower`|`Integer`|`false`|小红花数量
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": null
}
----
