:icons: font
:source-highlighter: highlightjs
:numbered:
:toc: left
:toclevels: 3


= 包妈课堂接口文档
chenjunqiang <chenjunqiang@xxbmm.com>
v1.0 2018-07-06


== 相关类别
=== 基础响应信息
[cols="4", options="header"]
|===
|参数|类型|说明|示例
|`success`|`boolean`|返回结果状态。true：成功；false：失败。|`true`
|`msg`|`String`|提示信息|操作成功
|`code`|`Integer`|响应码，可选|`0`
|`nowDate`|`Long`|当前时间戳|`1530773758000`
|`data`|`Object`|响应数据|`null`
|===
=== 分页响应信息
[cols="4", options="header"]
|===
|参数|类型|说明|示例
|`pageNum`|`Integer`|当前页|`1`
|`pageSize`|`Integer`|每页的数量|`10`
|`pages`|`Integer`|总页数|`5`
|`total`|`Integer`|总记录数|`55`
|`hasNextPage`|`boolean`|是否有下一页|`true`
|===
[#flowerType,asdsa]
=== 小红花记录类型
[cols="3", options="header"]
|===
|类型|值|描述
|课程兑换|`1`|兑换课程
|每日签到|`2`|每日签到
|连续签到|`3`|每连续签到7日
|邀请新用户|`4`|成功邀请新用户
|观看课程超过3分钟|`5`|观看课程超过3分钟，每节课持续观看超过3分钟
|发表留言|`6`|发表留言通过审核
|留言被推荐|`7`|留言被推荐
|留言被老师回复|`8`|留言被老师回复
|分享课程给好友|`9`|分享课程给好友
|分享课程被好友点击|`10`|分享课程被好友点击
|看完专辑课程|`11`|看完专辑课程，每看完一节课
|===

== 用户
=== 用户接口
==== 查询用户信息
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/{id}`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`id(path)`|`Integer`|`true`|用户编号
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1531127611915,
    "ver": 0,
    "data": {
        "id": 16,
        "name": "chenjq", //用户姓名
        "phone": "18310022931", //手机号码
        "headImage": "https://img.xxbmm.com/0.jpg", //头像url地址
        "flower": 52, //小红花数量
        "openId": "oPmunjkl72XsCZqFeowXoYqyGVOo", //openId
        "unionId": "oe3vZwEmfXUtr2BzcOSRfoZLc9Og", //unionId
        "status": 0, //冻结状态,0-正常，1-冻结
        "createTime": 1530773758000 //添加时间
    }
}
----
=== 用户红花接口
==== 红花记录分页查询
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/page`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`page`|`Integer`|`true`|当前页
|`pageSize`|`Integer`|`true`|每页数量
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": {
        "list": [
            {
              "id": 3 ,
              "userId": 16 ,  //用户编号
              "type": 1 , //类型值
              "objectId": 123 , //关联编号
              "friendUserId": 123 , //好友编号
              "description": "兑换课程,减少100积分，用户Id:{16},关联ID:{123}" , //记录描述
              "flower": 100 , //小红花数量
              "createTime": 1530773758000 , //添加时间
              "typeName": "课程兑换" , //类型名称
              "directionIcon": "-"  //扣减方向符号 +、-
            }
        ],
        "pageNum": 1,
        "pageSize": 2,
        "pages": 1,
        "total": 2,
        "hasNextPage": false
    }
}
----

==== 查询当日签到状态
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/signStatus`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": true  //签到状态 true、false
}
----

==== 更新小红花接口
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/flower/log/`|`POST`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`type`|`Integer`|`true`|记录类型 详细请阅读<<flowerType>>
|`objectId`|`Integer`|`false`|关联ID
|`friendUserId`|`Integer`|`false`|好友ID
|`flower`|`Integer`|`false`|小红花数量
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": null
}
----

=== 兑换课程接口
==== 已兑换课程分页查询
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/consume/page`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`page`|`Integer`|`true`|当前页
|`pageSize`|`Integer`|`true`|每页数量
|===
****
// WARNING: **//TODO 待定**

.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": {
        "list": [
          {
              "subject": {
                  "id": 1,
                  "title": "秃顶是怎样练成的",  //课程主题
                  "author": 1,  //作者id
                  "description": "程序员秃顶之路", //课程介绍
                  "banner": "http://www.banner.com", //课程banner，存储url
                  "type": 1,  //观看途径：0，免费，1，兑换，2，组团
                  "completed": 1, //连载状态 0:完成 1：连载中  单集视频默认0
                  "objectType": 1,  //对象属性：0，视频，1，音频
                  "upDownStatus": 1,  //上下架状态 0:上架 1:下架
                  "videoType": 1, //视频属性：0，单集，1，多集
                  "categoryId": null, //主题分类id
                  "flower": 1,  //小红花数量
                  "content": "这是一段测试内容" //内容描述
              },
              "author": {
                  "id": 1,
                  "name": "宋大善人", //名称
                  "headImage": "http://www.badiu.com.jpeg?seaerch=niudehua",  //头像url地址
                  "description": "不知名明星", //作者介绍
                  "socialTitle": "",  //社会头衔
                  "sex": 1  //性别，0-男，1-女
              },
              "videosList": [
                  {
                      "id": 39,
                      "subjectId": 1, //课程id
                      "videoName": "测试保存视频",  //视频名称
                      "videoUrl": "保存视频url",  //视频url
                      "timeLength": "111",  //视频时长
                      "experience": 0,  //是否为试看视频，0-非是看，1-试看
                      "sort": 1 //排序
                  }
              ]
          }
        ],
        "pageNum": 1,
        "pageSize": 2,
        "pages": 1,
        "total": 2,
        "hasNextPage": false
    }
}
----

==== 兑换课程
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/user/consume/`|`POST`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`subjectId`|`Integer`|`true`|课程ID
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": null
}
----

=== 组团课程接口
==== 组团中的课程分页查询
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/video/share/publish/page`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`page`|`Integer`|`true`|当前页
|`pageSize`|`Integer`|`true`|每页数量
|===
****
// WARNING: **//TODO 待定**

.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": {
        "list": [
          {
              "subject": {
                  "id": 1,
                  "title": "秃顶是怎样练成的",  //课程主题
                  "author": 1,  //作者id
                  "description": "程序员秃顶之路", //课程介绍
                  "banner": "http://www.banner.com", //课程banner，存储url
                  "type": 1,  //观看途径：0，免费，1，兑换，2，组团
                  "completed": 1, //连载状态 0:完成 1：连载中  单集视频默认0
                  "objectType": 1,  //对象属性：0，视频，1，音频
                  "upDownStatus": 1,  //上下架状态 0:上架 1:下架
                  "videoType": 1, //视频属性：0，单集，1，多集
                  "categoryId": null, //主题分类id
                  "flower": 1,  //小红花数量
                  "content": "这是一段测试内容" //内容描述
              },
              "author": {
                  "id": 1,
                  "name": "宋大善人", //名称
                  "headImage": "http://www.badiu.com.jpeg?seaerch=niudehua",  //头像url地址
                  "description": "不知名明星", //作者介绍
                  "socialTitle": "",  //社会头衔
                  "sex": 1  //性别，0-男，1-女
              },
              "videosList": [
                  {
                      "id": 39,
                      "subjectId": 1, //课程id
                      "videoName": "测试保存视频",  //视频名称
                      "videoUrl": "保存视频url",  //视频url
                      "timeLength": "111",  //视频时长
                      "experience": 0,  //是否为试看视频，0-非是看，1-试看
                      "sort": 1 //排序
                  }
              ],
              "vo": {
                  "id": 3,
                  "subjectId": 2, //课程id
                  "shareNum": 3,  //需要拼团人数
                  "userId": 16, //发起人id
                  "createTime": 1531382721000,
                  "currentCount": 1 //当前拼团人数
              }
          }
        ],
        "pageNum": 1,
        "pageSize": 2,
        "pages": 1,
        "total": 2,
        "hasNextPage": false
    }
}
----

==== 获取用户拼团详情
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/video/share/publish/userSubjectShare`|`GET`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`subjectId`|`Integer`|`true`|课程ID
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1531390813417,
    "ver": 0,
    "data": {
        "id": 3,
        "subjectId": 2, //课程ID
        "shareNum": 3,  //需要拼团人数
        "userId": 16,   //发起人id
        "createTime": 1531382721000,
        "joinList": [   //助力人列表
            {
                "id": 2,
                "videoSharePublishId": 3,   //拼团id
                "headImage": "https://img.xxbmm.com/image/1.jpg", //助力人头像url
                "userId": 1,  //助力人id
                "createTime": 1531383264000
            }
        ],
    }
}
----

==== 发起拼团
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/video/share/publish/`|`POST`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`subjectId`|`Integer`|`true`|课程ID
|`shareNum`|`Integer`|`true`|拼团人数
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": null
}
----
==== 助力拼团
[cols="3", options="header"]
|===
|URL|HTTP请求方式|返回格式
|`/video/share/join/`|`POST`|`JSON`
|===
.请求参数
****
[cols="4", options="header"]
|===
|参数|类型|必填|说明
|`userId`|`Integer`|`true`|用户编号
|`videoSharePublishId`|`Integer`|`true`|拼团ID
|===
****
.返回参数
[source,JSON]
----
{
    "success": true,
    "msg": "成功",
    "code": 0,
    "nowDate": 1530773758000,
    "data": null
}
----
